### ISSUE TITLE
Bug on double click to remove a node

### ISSUE THREAD

**Issue by raphaelramosds** [ErnaneJ/ds-simulator#1] opened 2023-03-20 23:11 UTC
I've implemented an event to remove nodes by double click, but it always remove the last element of the list once this event is triggered.

```js
  function handleNodeClick(event: React.MouseEvent, node: Node) {
    switch (event.detail) {
      case 1: {
        break;
      }
      case 2: {
        setIndexToChange(parseInt(node.data.index));
        removeNode();
        break;
      }
      default: {
        break;
      }
    }
  }
```

This event is passed by props on `ReactFlow` component on line 217

**Comment by ErnaneJ** [comment] 2023-03-21 01:02
We can solve this problem and shorten the code by overloading the `removeNode` method a little by passing an optional parameter. So, when it comes, we use the index passed and if it doesn't come, we use the state.

```ts
removeNode(index?: number):void
```

After that, the only check we'll have to do is the type of the parameter. Since an `ReactEvent` can come (caused by `ToolbarFooter`), a `number` (which is what we want) or `undefined`. Only when it is `number` we use it.

```ts
const indexToRemove = typeof index === 'number' ? index : indexToChange;
```

That way it is easy to remove by index when clicked. You can check the changes in my last commit (d301c89) on the dev branch.

If you like my suggestion we can close this issue.

**Closed as completed** 2023-03-21 09:49 UTC
Labels: bug
